from python:3.7

COPY . /app
WORKDIR /app

RUN pip install -r requirements.txt
RUN pip install Flask gunicorn

EXPOSE $PORT
# CMD exec gunicorn --bind 0.0.0.0:$PORT --workers=4 --threads 8 --timeout 0 app:app
CMD ['python', 'app.py']
